vich_uploader:
  db_driver: orm
  mappings:
    teams_images:
      uri_prefix: /uploads/images/teams
      upload_destination: "%kernel.project_dir%/public/uploads/images/teams"
      namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
      delete_on_remove: true
      delete_on_update: true
